export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
  popular?: boolean
  customizations?: {
    sizes?: { name: string; price: number }[]
    addons?: { name: string; price: number }[]
  }
}

export interface Category {
  id: string
  name: string
  icon: string
}

export const categories: Category[] = [
  { id: "burgers", name: "Burgers", icon: "🍔" },
  { id: "sides", name: "Sides", icon: "🍟" },
  { id: "drinks", name: "Drinks", icon: "🥤" },
  { id: "desserts", name: "Desserts", icon: "🍰" },
  { id: "pizzas", name: "Pizzas", icon: "🍕" },
  { id: "biryani", name: "Biryani", icon: "🍛" },
  { id: "noodles", name: "Noodle Bowls", icon: "🍜" },
  { id: "north-indian", name: "North Indian Dishes", icon: "🥘" },
  { id: "south-indian", name: "South Indian Dishes", icon: "🍲" },
  { id: "rolls-momos", name: "Rolls & Momos", icon: "🥟" }
];

export const menuItems: MenuItem[] = [
  // Burgers (10 items)
  {
    id: "classic-burger",
    name: "Classic Beef Burger",
    description: "Juicy beef patty with lettuce, tomato, onion, and our signature sauce",
    price: 12.99,
    image: "/classic-beef-burger.png",
    category: "burgers",
    popular: true,
    customizations: {
      sizes: [
        { name: "Regular", price: 0 },
        { name: "Large", price: 2.5 },
      ],
      addons: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Bacon", price: 2.0 },
        { name: "Avocado", price: 1.75 },
      ],
    },
  },
  {
    id: "chicken-deluxe",
    name: "Chicken Deluxe",
    description: "Crispy chicken breast with mayo, lettuce, and pickles on a toasted bun",
    price: 11.99,
    image: "/crispy-chicken-deluxe.png",
    category: "burgers",
    customizations: {
      sizes: [
        { name: "Regular", price: 0 },
        { name: "Large", price: 2.5 },
      ],
      addons: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Spicy Sauce", price: 0.5 },
      ],
    },
  },
  {
    id: "veggie-burger",
    name: "Garden Veggie Burger",
    description: "Plant-based patty with fresh vegetables and herb aioli",
    price: 10.99,
    image: "/veggie-burger-with-fresh-ingredients.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Vegan Cheese", price: 1.5 },
        { name: "Grilled Mushrooms", price: 1.25 },
      ],
    },
  },
  {
    id: "double-cheese-burger",
    name: "Double Cheese Burger",
    description: "Two beef patties with double cheese, lettuce, tomato, and special sauce",
    price: 15.99,
    image: "/double-cheese-burger.png",
    category: "burgers",
    popular: true,
    customizations: {
      addons: [
        { name: "Extra Patty", price: 3.0 },
        { name: "Bacon", price: 2.0 },
        { name: "Grilled Onions", price: 1.0 },
      ],
    },
  },
  {
    id: "spicy-chicken-burger",
    name: "Spicy Chicken Burger",
    description: "Grilled chicken with spicy mayo, jalapeños, and pepper jack cheese",
    price: 12.49,
    image: "/spicy-chicken-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Jalapeños", price: 0.75 },
        { name: "Avocado", price: 1.75 },
      ],
    },
  },
  {
    id: "bbq-bacon-burger",
    name: "BBQ Bacon Burger",
    description: "Beef patty with BBQ sauce, crispy bacon, onion rings, and cheddar cheese",
    price: 14.99,
    image: "/bbq-bacon-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Bacon", price: 2.0 },
        { name: "Smoked Cheese", price: 1.5 },
      ],
    },
  },
  {
    id: "mushroom-swiss-burger",
    name: "Mushroom Swiss Burger",
    description: "Beef patty with sautéed mushrooms, Swiss cheese, and truffle aioli",
    price: 13.99,
    image: "/mushroom-swiss-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Mushrooms", price: 1.25 },
        { name: "Truffle Fries", price: 3.0 },
      ],
    },
  },
  {
    id: "fish-burger",
    name: "Crispy Fish Burger",
    description: "Beer-battered fish fillet with lettuce, tomato, and tartar sauce",
    price: 11.49,
    image: "/crispy-fish-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Tartar Sauce", price: 0.5 },
        { name: "Pickles", price: 0.25 },
      ],
    },
  },
  {
    id: "turkey-avocado-burger",
    name: "Turkey Avocado Burger",
    description: "Lean turkey patty with fresh avocado, spinach, and ranch dressing",
    price: 12.49,
    image: "/turkey-avocado-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Avocado", price: 1.75 },
        { name: "Turkey Bacon", price: 1.5 },
      ],
    },
  },
  {
    id: "lamb-burger",
    name: "Mediterranean Lamb Burger",
    description: "Seasoned lamb patty with feta cheese, cucumber, and tzatziki sauce",
    price: 16.99,
    image: "/mediterranean-lamb-burger.png",
    category: "burgers",
    customizations: {
      addons: [
        { name: "Extra Feta", price: 1.5 },
        { name: "Red Onion", price: 0.5 },
      ],
    },
  },

  // Sides (15 items)
  {
    id: "golden-fries",
    name: "Golden Fries",
    description: "Crispy golden fries seasoned with sea salt",
    price: 4.99,
    image: "/golden-crispy-fries.png",
    category: "sides",
    popular: true,
    customizations: {
      sizes: [
        { name: "Small", price: 0 },
        { name: "Medium", price: 1.5 },
        { name: "Large", price: 2.5 },
      ],
    },
  },
  {
    id: "onion-rings",
    name: "Crispy Onion Rings",
    description: "Beer-battered onion rings served with ranch dipping sauce",
    price: 5.99,
    image: "/crispy-onion-rings.png",
    category: "sides",
  },
  {
    id: "chicken-nuggets",
    name: "Chicken Nuggets",
    description: "Tender chicken nuggets with your choice of dipping sauce",
    price: 7.99,
    image: "/golden-chicken-nuggets.png",
    category: "sides",
    customizations: {
      sizes: [
        { name: "6 pieces", price: 0 },
        { name: "10 pieces", price: 2.5 },
        { name: "20 pieces", price: 5.0 },
      ],
    },
  },
  {
    id: "sweet-potato-fries",
    name: "Sweet Potato Fries",
    description: "Crispy sweet potato fries with cinnamon sugar and maple dipping sauce",
    price: 6.49,
    image: "/sweet-potato-fries.png",
    category: "sides",
    popular: true,
  },
  {
    id: "mozzarella-sticks",
    name: "Mozzarella Sticks",
    description: "Breaded mozzarella sticks served with marinara sauce",
    price: 6.99,
    image: "/mozzarella-sticks.png",
    category: "sides",
    customizations: {
      sizes: [
        { name: "6 pieces", price: 0 },
        { name: "10 pieces", price: 3.0 },
      ],
    },
  },
  {
    id: "buffalo-wings",
    name: "Buffalo Wings",
    description: "Spicy buffalo wings with blue cheese dip and celery sticks",
    price: 9.99,
    image: "/buffalo-wings.png",
    category: "sides",
    customizations: {
      sizes: [
        { name: "6 pieces", price: 0 },
        { name: "12 pieces", price: 4.0 },
        { name: "24 pieces", price: 8.0 },
      ],
    },
  },
  {
    id: "loaded-nachos",
    name: "Loaded Nachos",
    description: "Tortilla chips with cheese, jalapeños, sour cream, and guacamole",
    price: 8.99,
    image: "/loaded-nachos.png",
    category: "sides",
    customizations: {
      addons: [
        { name: "Ground Beef", price: 2.5 },
        { name: "Extra Guacamole", price: 1.5 },
      ],
    },
  },
  {
    id: "garlic-bread",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter and herbs",
    price: 4.49,
    image: "/garlic-bread.png",
    category: "sides",
    customizations: {
      addons: [
        { name: "Extra Cheese", price: 1.0 },
        { name: "Herbs", price: 0.5 },
      ],
    },
  },
  {
    id: "coleslaw",
    name: "Creamy Coleslaw",
    description: "Fresh cabbage and carrot slaw with creamy dressing",
    price: 3.99,
    image: "/creamy-coleslaw.png",
    category: "sides",
  },
  {
    id: "mac-and-cheese",
    name: "Mac and Cheese",
    description: "Creamy macaroni and cheese with breadcrumb topping",
    price: 5.99,
    image: "/mac-and-cheese.png",
    category: "sides",
    customizations: {
      addons: [
        { name: "Bacon Bits", price: 1.5 },
        { name: "Jalapeños", price: 0.75 },
      ],
    },
  },
  {
    id: "potato-wedges",
    name: "Seasoned Potato Wedges",
    description: "Thick-cut potato wedges with herbs and spices",
    price: 5.49,
    image: "/seasoned-potato-wedges.png",
    category: "sides",
    customizations: {
      addons: [
        { name: "Sour Cream", price: 0.75 },
        { name: "Cheese Sauce", price: 1.0 },
      ],
    },
  },
  {
    id: "jalapeno-poppers",
    name: "Jalapeño Poppers",
    description: "Cream cheese stuffed jalapeños wrapped in bacon",
    price: 7.49,
    image: "/jalapeno-poppers.png",
    category: "sides",
  },
  {
    id: "corn-on-cob",
    name: "Grilled Corn on the Cob",
    description: "Buttery grilled corn with herbs and parmesan",
    price: 3.99,
    image: "/grilled-corn-cob.png",
    category: "sides",
  },
  {
    id: "chicken-tenders",
    name: "Chicken Tenders",
    description: "Crispy chicken tenders with honey mustard sauce",
    price: 8.49,
    image: "/chicken-tenders.png",
    category: "sides",
    customizations: {
      sizes: [
        { name: "3 pieces", price: 0 },
        { name: "5 pieces", price: 2.0 },
        { name: "8 pieces", price: 4.0 },
      ],
    },
  },
  {
    id: "stuffed-mushrooms",
    name: "Stuffed Mushrooms",
    description: "Mushroom caps stuffed with cream cheese, herbs, and breadcrumbs",
    price: 6.99,
    image: "/stuffed-mushrooms.png",
    category: "sides",
  },

  // Drinks (12 items)
  {
    id: "cola",
    name: "Classic Cola",
    description: "Refreshing cola with ice",
    price: 2.99,
    image: "/cola-with-ice.png",
    category: "drinks",
    customizations: {
      sizes: [
        { name: "Small", price: 0 },
        { name: "Medium", price: 0.5 },
        { name: "Large", price: 1.0 },
      ],
    },
  },
  {
    id: "milkshake",
    name: "Vanilla Milkshake",
    description: "Creamy vanilla milkshake topped with whipped cream",
    price: 4.99,
    image: "/vanilla-milkshake.png",
    category: "drinks",
    popular: true,
  },
  {
    id: "orange-juice",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 3.99,
    image: "/fresh-orange-juice.png",
    category: "drinks",
  },
  {
    id: "chocolate-milkshake",
    name: "Chocolate Milkshake",
    description: "Rich chocolate milkshake with chocolate chips",
    price: 5.49,
    image: "/chocolate-milkshake.png",
    category: "drinks",
    popular: true,
  },
  {
    id: "strawberry-milkshake",
    name: "Strawberry Milkshake",
    description: "Fresh strawberry milkshake with real strawberry pieces",
    price: 5.49,
    image: "/strawberry-milkshake.png",
    category: "drinks",
  },
  {
    id: "iced-coffee",
    name: "Iced Coffee",
    description: "Cold brew coffee served over ice with cream",
    price: 3.49,
    image: "/iced-coffee.png",
    category: "drinks",
    customizations: {
      addons: [
        { name: "Extra Shot", price: 0.75 },
        { name: "Vanilla Syrup", price: 0.5 },
      ],
    },
  },
  {
    id: "lemonade",
    name: "Fresh Lemonade",
    description: "Freshly squeezed lemonade with mint",
    price: 3.49,
    image: "/fresh-lemonade.png",
    category: "drinks",
  },
  {
    id: "sprite",
    name: "Lemon-Lime Soda",
    description: "Crisp lemon-lime soda",
    price: 2.99,
    image: "/lemon-lime-soda.png",
    category: "drinks",
    customizations: {
      sizes: [
        { name: "Small", price: 0 },
        { name: "Medium", price: 0.5 },
        { name: "Large", price: 1.0 },
      ],
    },
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    description: "Rich hot chocolate with marshmallows",
    price: 3.99,
    image: "/hot-chocolate.png",
    category: "drinks",
    customizations: {
      addons: [
        { name: "Extra Marshmallows", price: 0.5 },
        { name: "Whipped Cream", price: 0.75 },
      ],
    },
  },
  {
    id: "green-tea",
    name: "Green Tea",
    description: "Fresh brewed green tea",
    price: 2.49,
    image: "/green-tea.png",
    category: "drinks",
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    description: "Traditional yogurt-based mango drink",
    price: 4.49,
    image: "/mango-lassi.png",
    category: "drinks",
    popular: true,
  },
  {
    id: "water-bottle",
    name: "Bottled Water",
    description: "Pure bottled water",
    price: 1.99,
    image: "/bottled-water.png",
    category: "drinks",
  },

  // Desserts (10 items)
  {
    id: "chocolate-cake",
    name: "Chocolate Fudge Cake",
    description: "Rich chocolate cake with fudge frosting",
    price: 5.99,
    image: "/chocolate-fudge-cake-slice.png",
    category: "desserts",
  },
  {
    id: "ice-cream",
    name: "Vanilla Ice Cream",
    description: "Creamy vanilla ice cream with chocolate chips",
    price: 3.99,
    image: "/vanilla-chocolate-chip-ice-cream.png",
    category: "desserts",
    customizations: {
      addons: [
        { name: "Extra Chocolate Chips", price: 0.75 },
        { name: "Caramel Sauce", price: 0.5 },
      ],
    },
  },
  {
    id: "cheesecake",
    name: "New York Cheesecake",
    description: "Classic New York style cheesecake with berry compote",
    price: 6.99,
    image: "/new-york-cheesecake.png",
    category: "desserts",
    popular: true,
  },
  {
    id: "apple-pie",
    name: "Apple Pie",
    description: "Homestyle apple pie with cinnamon and vanilla ice cream",
    price: 5.49,
    image: "/apple-pie.png",
    category: "desserts",
    customizations: {
      addons: [
        { name: "Vanilla Ice Cream", price: 1.5 },
        { name: "Whipped Cream", price: 0.75 },
      ],
    },
  },
  {
    id: "tiramisu",
    name: "Tiramisu",
    description: "Classic Italian tiramisu with coffee and mascarpone",
    price: 6.49,
    image: "/tiramisu.png",
    category: "desserts",
  },
  {
    id: "chocolate-brownie",
    name: "Chocolate Brownie",
    description: "Warm chocolate brownie with nuts and ice cream",
    price: 4.99,
    image: "/chocolate-brownie.png",
    category: "desserts",
    customizations: {
      addons: [
        { name: "Vanilla Ice Cream", price: 1.5 },
        { name: "Hot Fudge", price: 1.0 },
      ],
    },
  },
  {
    id: "fruit-tart",
    name: "Mixed Fruit Tart",
    description: "Fresh seasonal fruits on vanilla custard tart",
    price: 5.99,
    image: "/mixed-fruit-tart.png",
    category: "desserts",
  },
  {
    id: "cookies",
    name: "Chocolate Chip Cookies",
    description: "Fresh baked chocolate chip cookies (3 pieces)",
    price: 3.49,
    image: "/chocolate-chip-cookies.png",
    category: "desserts",
    customizations: {
      sizes: [
        { name: "3 pieces", price: 0 },
        { name: "6 pieces", price: 2.0 },
      ],
    },
  },
  {
    id: "panna-cotta",
    name: "Vanilla Panna Cotta",
    description: "Silky vanilla panna cotta with berry sauce",
    price: 5.49,
    image: "/vanilla-panna-cotta.png",
    category: "desserts",
  },
  {
    id: "gelato",
    name: "Pistachio Gelato",
    description: "Authentic Italian pistachio gelato",
    price: 4.99,
    image: "/pistachio-gelato.png",
    category: "desserts",
    popular: true,
  },

  // Pizzas (12 items)
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    price: 14.99,
    image: "/margherita-pizza.png",
    category: "pizzas",
    popular: true,
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
      addons: [
        { name: "Extra Cheese", price: 2.0 },
        { name: "Extra Basil", price: 1.0 },
      ],
    },
  },
  {
    id: "pepperoni-pizza",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni pizza with mozzarella cheese",
    price: 16.99,
    image: "/pepperoni-pizza.png",
    category: "pizzas",
    popular: true,
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
      addons: [
        { name: "Extra Pepperoni", price: 2.5 },
        { name: "Mushrooms", price: 1.5 },
      ],
    },
  },
  {
    id: "veggie-supreme-pizza",
    name: "Veggie Supreme Pizza",
    description: "Bell peppers, mushrooms, onions, olives, and tomatoes",
    price: 15.99,
    image: "/veggie-supreme-pizza.png",
    category: "pizzas",
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
    },
  },
  {
    id: "meat-lovers-pizza",
    name: "Meat Lovers Pizza",
    description: "Pepperoni, sausage, bacon, and ham with extra cheese",
    price: 19.99,
    image: "/meat-lovers-pizza.png",
    category: "pizzas",
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
    },
  },
  {
    id: "bbq-chicken-pizza",
    name: "BBQ Chicken Pizza",
    description: "BBQ sauce, grilled chicken, red onions, and cilantro",
    price: 17.99,
    image: "/bbq-chicken-pizza.png",
    category: "pizzas",
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
    },
  },
  {
    id: "hawaiian-pizza",
    name: "Hawaiian Pizza",
    description: "Ham and pineapple with mozzarella cheese",
    price: 16.49,
    image: "/hawaiian-pizza.png",
    category: "pizzas",
    customizations: {
      sizes: [
        { name: "Small (8\")", price: 0 },
        { name: "Medium (10\")", price: 3.0 },
        { name: "Large (12\")", price: 5.0 },
      ],
    },
  },
  {
    id: "white-pizza",
    name: "White Pizza",
    description: "Ricotta, mozzarella, garlic, and fresh herbs",
    price: 15.49,
    image: "/white-pizza.png",
    category: "pizzas",
  },
  {
    id: "buffalo-chicken-pizza",
    name: "Buffalo Chicken Pizza",
    description: "Spicy buffalo chicken with blue cheese and celery",
    price: 18.49,
    image: "/buffalo-chicken-pizza.png",
    category: "pizzas",
  },
  {
    id: "mushroom-pizza",
    name: "Mushroom Pizza",
    description: "Mixed mushrooms with garlic and herbs",
    price: 14.99,
    image: "/mushroom-pizza.png",
    category: "pizzas",
  },
  {
    id: "four-cheese-pizza",
    name: "Four Cheese Pizza",
    description: "Mozzarella, parmesan, gorgonzola, and goat cheese",
    price: 17.49,
    image: "/four-cheese-pizza.png",
    category: "pizzas",
  },
  {
    id: "seafood-pizza",
    name: "Seafood Pizza",
    description: "Shrimp, calamari, and fresh herbs with white sauce",
    price: 21.99,
    image: "/seafood-pizza.png",
    category: "pizzas",
  },
  {
    id: "veggie-pesto-pizza",
    name: "Veggie Pesto Pizza",
    description: "Pesto sauce with sun-dried tomatoes, spinach, and artichokes",
    price: 16.99,
    image: "/veggie-pesto-pizza.png",
    category: "pizzas",
  },

  // Biryani (10 items)
  {
    id: "chicken-biryani",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice with tender chicken and traditional spices",
    price: 16.99,
    image: "/chicken-biryani.png",
    category: "biryani",
    popular: true,
    customizations: {
      addons: [
        { name: "Raita", price: 2.0 },
        { name: "Pickle", price: 1.0 },
        { name: "Boiled Egg", price: 1.5 },
      ],
    },
  },
  {
    id: "mutton-biryani",
    name: "Mutton Biryani",
    description: "Traditional mutton biryani with fragrant spices and saffron",
    price: 19.99,
    image: "/mutton-biryani.png",
    category: "biryani",
    popular: true,
    customizations: {
      addons: [
        { name: "Raita", price: 2.0 },
        { name: "Pickle", price: 1.0 },
      ],
    },
  },
  {
    id: "veg-biryani",
    name: "Vegetable Biryani",
    description: "Mixed vegetables cooked with aromatic basmati rice",
    price: 13.99,
    image: "/vegetable-biryani.png",
    category: "biryani",
    customizations: {
      addons: [
        { name: "Raita", price: 2.0 },
        { name: "Pickle", price: 1.0 },
      ],
    },
  },
  {
    id: "fish-biryani",
    name: "Fish Biryani",
    description: "Fresh fish cooked with basmati rice and coastal spices",
    price: 18.49,
    image: "/fish-biryani.png",
    category: "biryani",
  },
  {
    id: "prawn-biryani",
    name: "Prawn Biryani",
    description: "Succulent prawns with aromatic rice and special spices",
    price: 20.99,
    image: "/prawn-biryani.png",
    category: "biryani",
  },
  {
    id: "egg-biryani",
    name: "Egg Biryani",
    description: "Hard-boiled eggs cooked with spiced basmati rice",
    price: 12.99,
    image: "/egg-biryani.png",
    category: "biryani",
  },
  {
    id: "paneer-biryani",
    name: "Paneer Biryani",
    description: "Cottage cheese cubes with fragrant rice and mild spices",
    price: 15.49,
    image: "/paneer-biryani.png",
    category: "biryani",
  },
  {
    id: "hyderabadi-biryani",
    name: "Hyderabadi Dum Biryani",
    description: "Authentic Hyderabadi style dum biryani with tender meat and saffron",
    price: 21.99,
    image: "/hyderabadi-dum-biryani.png",
    category: "biryani",
    popular: true,
  },
  {
    id: "kolkata-biryani",
    name: "Kolkata Biryani",
    description: "Bengali style biryani with potato and subtle flavors",
    price: 17.49,
    image: "/kolkata-biryani.png",
    category: "biryani",
  },
  {
    id: "lucknowi-biryani",
    name: "Lucknowi Biryani",
    description: "Awadhi style biryani cooked in traditional dum method",
    price: 20.49,
    image: "/lucknowi-biryani.png",
    category: "biryani",
  },

  // Noodles (12 items)
  {
    id: "chicken-hakka-noodles",
    name: "Chicken Hakka Noodles",
    description: "Stir-fried noodles with chicken, vegetables, and soy sauce",
    price: 12.99,
    image: "/chicken-hakka-noodles.png",
    category: "noodles",
    popular: true,
  },
  {
    id: "veg-hakka-noodles",
    name: "Vegetable Hakka Noodles",
    description: "Stir-fried noodles with mixed vegetables and aromatic spices",
    price: 10.99,
    image: "/vegetable-hakka-noodles.png",
    category: "noodles",
  },
  {
    id: "schezwan-noodles",
    name: "Schezwan Noodles",
    description: "Spicy noodles with schezwan sauce and vegetables",
    price: 11.99,
    image: "/schezwan-noodles.png",
    category: "noodles",
    popular: true,
    customizations: {
      addons: [
        { name: "Extra Chicken", price: 3.0 },
        { name: "Extra Vegetables", price: 2.0 },
      ],
    },
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    description: "Thai style stir-fried rice noodles with tamarind and peanuts",
    price: 13.49,
    image: "/pad-thai.png",
    category: "noodles",
  },
  {
    id: "singapore-noodles",
    name: "Singapore Rice Noodles",
    description: "Curry-flavored rice noodles with shrimp and char siu",
    price: 14.99,
    image: "/singapore-noodles.png",
    category: "noodles",
  },
  {
    id: "lo-mein",
    name: "Chicken Lo Mein",
    description: "Soft noodles with chicken and vegetables in savory sauce",
    price: 12.49,
    image: "/chicken-lo-mein.png",
    category: "noodles",
  },
  {
    id: "ramen-bowl",
    name: "Chicken Ramen Bowl",
    description: "Japanese style ramen with chicken broth and toppings",
    price: 14.49,
    image: "/chicken-ramen-bowl.png",
    category: "noodles",
    popular: true,
    customizations: {
      addons: [
        { name: "Soft-boiled Egg", price: 1.5 },
        { name: "Extra Chicken", price: 2.5 },
        { name: "Nori", price: 1.0 },
      ],
    },
  },
  {
    id: "pho-bo",
    name: "Vietnamese Pho Bo",
    description: "Traditional Vietnamese beef noodle soup with herbs",
    price: 13.99,
    image: "/pho-bo.png",
    category: "noodles",
  },
  {
    id: "drunken-noodles",
    name: "Drunken Noodles",
    description: "Thai wide rice noodles with basil and chili",
    price: 12.99,
    image: "/drunken-noodles.png",
    category: "noodles",
  },
  {
    id: "beef-chow-mein",
    name: "Beef Chow Mein",
    description: "Crispy noodles with beef and vegetables",
    price: 13.99,
    image: "/beef-chow-mein.png",
    category: "noodles",
  },
  {
    id: "udon-soup",
    name: "Chicken Udon Soup",
    description: "Japanese thick noodles in savory broth with chicken",
    price: 12.99,
    image: "/chicken-udon-soup.png",
    category: "noodles",
  },
  {
    id: "tom-yum-noodles",
    name: "Tom Yum Noodles",
    description: "Spicy and sour Thai noodle soup with shrimp",
    price: 14.99,
    image: "/tom-yum-noodles.png",
    category: "noodles",
  },

  // North Indian Dishes (15 items)
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Creamy tomato-based chicken curry with aromatic spices",
    price: 15.99,
    image: "/butter-chicken.png",
    category: "north-indian",
    popular: true,
    customizations: {
      addons: [
        { name: "Naan", price: 2.5 },
        { name: "Rice", price: 2.0 },
      ],
    },
  },
  {
    id: "chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    description: "Grilled chicken in rich tomato and cream sauce",
    price: 16.49,
    image: "/chicken-tikka-masala.png",
    category: "north-indian",
    popular: true,
  },
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    description: "Creamy black lentils cooked with butter and cream",
    price: 11.99,
    image: "/dal-makhani.png",
    category: "north-indian",
    customizations: {
      addons: [
        { name: "Naan", price: 2.5 },
        { name: "Rice", price: 2.0 },
      ],
    },
  },
  {
    id: "paneer-butter-masala",
    name: "Paneer Butter Masala",
    description: "Cottage cheese cubes in rich tomato and butter gravy",
    price: 13.99,
    image: "/paneer-butter-masala.png",
    category: "north-indian",
    popular: true,
  },
  {
    id: "chicken-korma",
    name: "Chicken Korma",
    description: "Mild chicken curry with yogurt and cashew gravy",
    price: 15.49,
    image: "/chicken-korma.png",
    category: "north-indian",
  },
  {
    id: "rogan-josh",
    name: "Mutton Rogan Josh",
    description: "Kashmiri style mutton curry with aromatic spices",
    price: 18.99,
    image: "/mutton-rogan-josh.png",
    category: "north-indian",
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    description: "Cottage cheese in creamy spinach gravy",
    price: 12.99,
    image: "/palak-paneer.png",
    category: "north-indian",
  },
  {
    id: "chole-bhature",
    name: "Chole Bhature",
    description: "Spicy chickpea curry with deep-fried bread",
    price: 10.99,
    image: "/chole-bhature.png",
    category: "north-indian",
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken",
    description: "Marinated chicken grilled in tandoor oven",
    price: 14.99,
    image: "/tandoori-chicken.png",
    category: "north-indian",
  },
  {
    id: "naan-bread",
    name: "Garlic Naan",
    description: "Indian flatbread with garlic and herbs",
    price: 3.99,
    image: "/garlic-naan.png",
    category: "north-indian",
    customizations: {
      addons: [
        { name: "Cheese", price: 1.5 },
        { name: "Butter", price: 0.75 },
      ],
    },
  },
  {
    id: "chicken-biryani-north",
    name: "Lucknowi Chicken Biryani",
    description: "Aromatic chicken biryani in Awadhi style",
    price: 17.99,
    image: "/lucknowi-chicken-biryani.png",
    category: "north-indian",
  },
  {
    id: "kadai-chicken",
    name: "Kadai Chicken",
    description: "Spicy chicken cooked with bell peppers and onions",
    price: 15.99,
    image: "/kadai-chicken.png",
    category: "north-indian",
  },
  {
    id: "malai-kofta",
    name: "Malai Kofta",
    description: "Fried cottage cheese balls in creamy gravy",
    price: 13.49,
    image: "/malai-kofta.png",
    category: "north-indian",
  },
  {
    id: "aloo-gobi",
    name: "Aloo Gobi",
    description: "Potato and cauliflower curry with spices",
    price: 9.99,
    image: "/aloo-gobi.png",
    category: "north-indian",
  },
  {
    id: "rajma-rice",
    name: "Rajma Rice",
    description: "Red kidney bean curry served with rice",
    price: 11.49,
    image: "/rajma-rice.png",
    category: "north-indian",
  },

  // South Indian Dishes (12 items)
  {
    id: "dosa-masala",
    name: "Masala Dosa",
    description: "Crispy rice crepe with spiced potato filling",
    price: 8.99,
    image: "/masala-dosa.png",
    category: "south-indian",
    popular: true,
    customizations: {
      addons: [
        { name: "Extra Chutney", price: 1.0 },
        { name: "Sambar", price: 1.5 },
      ],
    },
  },
  {
    id: "idli-sambar",
    name: "Idli Sambar",
    description: "Steamed rice cakes with lentil soup and chutney",
    price: 6.99,
    image: "/idli-sambar.png",
    category: "south-indian",
    popular: true,
  },
  {
    id: "uttapam",
    name: "Mixed Vegetable Uttapam",
    description: "Thick pancake with vegetables and spices",
    price: 7.99,
    image: "/mixed-vegetable-uttapam.png",
    category: "south-indian",
  },
  {
    id: "vada-sambar",
    name: "Medu Vada with Sambar",
    description: "Fried lentil donuts with spiced lentil soup",
    price: 6.49,
    image: "/medu-vada-sambar.png",
    category: "south-indian",
  },
  {
    id: "chicken-chettinad",
    name: "Chicken Chettinad",
    description: "Spicy South Indian chicken curry with coconut",
    price: 16.99,
    image: "/chicken-chettinad.png",
    category: "south-indian",
    popular: true,
  },
  {
    id: "fish-curry-south",
    name: "Kerala Fish Curry",
    description: "Fish cooked in coconut milk with curry leaves",
    price: 17.49,
    image: "/kerala-fish-curry.png",
    category: "south-indian",
  },
  {
    id: "rasam",
    name: "Tomato Rasam",
    description: "Tangy South Indian soup with tamarind and spices",
    price: 4.99,
    image: "/tomato-rasam.png",
    category: "south-indian",
  },
  {
    id: "sambar-rice",
    name: "Sambar Rice",
    description: "Rice mixed with lentil curry and vegetables",
    price: 8.49,
    image: "/sambar-rice.png",
    category: "south-indian",
  },
  {
    id: "coconut-rice",
    name: "Coconut Rice",
    description: "Fragrant rice cooked with coconut and curry leaves",
    price: 7.99,
    image: "/coconut-rice.png",
    category: "south-indian",
  },
  {
    id: "prawn-curry-south",
    name: "Malabar Prawn Curry",
    description: "Kerala style prawn curry with coconut milk",
    price: 19.99,
    image: "/malabar-prawn-curry.png",
    category: "south-indian",
  },
  {
    id: "appam",
    name: "Appam with Stew",
    description: "Fermented rice pancakes with vegetable stew",
    price: 9.99,
    image: "/appam-with-stew.png",
    category: "south-indian",
  },
  {
    id: "bisi-bele-bath",
    name: "Bisi Bele Bath",
    description: "Spicy Karnataka rice dish with lentils and vegetables",
    price: 10.49,
    image: "/bisi-bele-bath.png",
    category: "south-indian",
  },

  // Rolls & Momos (15 items)
  {
    id: "chicken-roll",
    name: "Chicken Kathi Roll",
    description: "Spiced chicken wrapped in paratha with onions and chutney",
    price: 8.99,
    image: "/chicken-kathi-roll.png",
    category: "rolls-momos",
    popular: true,
  },
  {
    id: "mutton-roll",
    name: "Mutton Seekh Roll",
    description: "Grilled mutton seekh wrapped in roomali roti",
    price: 10.99,
    image: "/mutton-seekh-roll.png",
    category: "rolls-momos",
  },
  {
    id: "paneer-roll",
    name: "Paneer Tikka Roll",
    description: "Grilled paneer with vegetables in wheat wrap",
    price: 7.99,
    image: "/paneer-tikka-roll.png",
    category: "rolls-momos",
  },
  {
    id: "egg-roll",
    name: "Egg Roll",
    description: "Scrambled eggs with onions and spices in paratha",
    price: 6.99,
    image: "/egg-roll.png",
    category: "rolls-momos",
  },
  {
    id: "veg-momos",
    name: "Vegetable Momos",
    description: "Steamed dumplings filled with mixed vegetables",
    price: 7.99,
    image: "/vegetable-momos.png",
    category: "rolls-momos",
    popular: true,
    customizations: {
      sizes: [
        { name: "6 pieces", price: 0 },
        { name: "10 pieces", price: 3.0 },
      ],
      addons: [
        { name: "Spicy Chutney", price: 1.0 },
        { name: "Mayo Dip", price: 0.75 },
      ],
    },
  },
  {
    id: "chicken-momos",
    name: "Chicken Momos",
    description: "Juicy chicken dumplings with aromatic spices",
    price: 9.99,
    image: "/chicken-momos.png",
    category: "rolls-momos",
    popular: true,
    customizations: {
      sizes: [
        { name: "6 pieces", price: 0 },
        { name: "10 pieces", price: 3.0 },
      ],
    },
  },
  {
    id: "pork-momos",
    name: "Pork Momos",
    description: "Traditional pork momos with ginger and garlic",
    price: 10.99,
    image: "/pork-momos.png",
    category: "rolls-momos",
  },
  {
    id: "fried-momos",
    name: "Fried Chicken Momos",
    description: "Crispy fried chicken momos with spicy dipping sauce",
    price: 11.49,
    image: "/fried-chicken-momos.png",
    category: "rolls-momos",
  },
  {
    id: "tandoori-momos",
    name: "Tandoori Momos",
    description: "Grilled momos with tandoori spices and mint chutney",
    price: 12.49,
    image: "/tandoori-momos.png",
    category: "rolls-momos",
  },
  {
    id: "cheese-momos",
    name: "Cheese Momos",
    description: "Vegetable momos with melted cheese filling",
    price: 9.49,
    image: "/cheese-momos.png",
    category: "rolls-momos",
  },
  {
    id: "fish-roll",
    name: "Fish Tikka Roll",
    description: "Grilled fish with salad wrapped in naan",
    price: 9.99,
    image: "/fish-tikka-roll.png",
    category: "rolls-momos",
  },
  {
    id: "aloo-roll",
    name: "Aloo Tikki Roll",
    description: "Spiced potato cutlet with chutneys in paratha",
    price: 5.99,
    image: "/aloo-tikki-roll.png",
    category: "rolls-momos",
  },
  {
    id: "chicken-tikka-roll",
    name: "Chicken Tikka Roll",
    description: "Grilled chicken tikka with mint chutney in wrap",
    price: 9.49,
    image: "/chicken-tikka-roll.png",
    category: "rolls-momos",
  },
  {
    id: "schezwan-momos",
    name: "Schezwan Momos",
    description: "Spicy momos tossed in schezwan sauce",
    price: 10.99,
    image: "/schezwan-momos.png",
    category: "rolls-momos",
  },
  {
    id: "chilli-momos",
    name: "Chilli Momos",
    description: "Indo-Chinese style momos with bell peppers and onions",
    price: 11.99,
    image: "/chilli-momos.png",
    category: "rolls-momos",
  },
];

export const getMenuItemsByCategory = (categoryId: string): MenuItem[] => {
  return menuItems.filter((item) => item.category === categoryId)
}

export const getPopularItems = (): MenuItem[] => {
  return menuItems.filter((item) => item.popular)
}